name: LAB | Setting Up a CI/CD Pipeline for a Multi-Page React Native Mobile App

on:
  push:
    branches:
        - main

jobs:
  build:
    name: LAB | Android
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: npm install

      - name: Validate TypeScript
        run: npx tsc --noEmit

      - name: Run Unit Tests
        run: npm test
